name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - scipy
  - numpy
  - nbsphinx
  - m2r >=0.2.1
  - numpydoc
  - sphinx
  - sphinx_rtd_theme



    # Pip-only installs
  #- pip:

