name: docs
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - pip
  - scipy
  - numpy
  - pint
  - sphinx
  - sphinx_rtd_theme
  - matplotlib



    # Pip-only installs
  #- pip:

